esphome:
  name: "${device_name}"
  friendly_name: "${device_friendly_name}"
  name_add_mac_suffix: true

logger:
  level: INFO

# project:
#     name: "ellar.${device_name}"
#     version: "${device_version}"
